[project]
name = "signoz-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
dependencies = [
    "Flask==3.0.0",
    "pyyaml==6.0.1",
    "requests==2.31.0",
]

[project.scripts]
signoz-mcp-server = "signoz_mcp_server.mcp_server:main"

[project.optional-dependencies]
prod = [
    "gunicorn",
]

[tool.hatch.build]
exclude = [
    "**/__pycache__",
    "**/*.pyc",
    "**/*.pyo",
    "**/*.pyd",
    "**/.venv",
    "**/env",
    "**/.ruff_cache"
]