# Signoz MCP Server Configuration
# Edit these values to match your Signoz instance

signoz:
  # Your Signoz instance URL (include http/https)
  host: "https://microservices-signoz.demo.drdroid.io"
  
  # Signoz API key if required (optional)
  api_key: "hrCw98ObIexp5Irl36H7D+qRlnaWuoPPXknozXyBtJI="
  
  # SSL verification (true/false)
  # Set to false only if using self-signed certificates
  ssl_verify: "true"

# Server configuration
server:
  port: 8000
  debug: true 