[project]
name = "signoz-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "Flask==3.0.0",
    "pyyaml==6.0.1",
    "requests==2.31.0",
]

