# Signoz MCP Server Configuration
# Edit these values to match your Signoz instance

signoz:
  # Your Signoz instance URL (include http/https)
  host: <host>
  
  # Signoz API key if required (optional)
  api_key: <api_key>
  
  # SSL verification (true/false)
  # Set to false only if using self-signed certificates
  ssl_verify: <ssl_verify>

# Server configuration
server:
  port: 8000
  debug: true

# This is for testing purposes only
openai:
  api_key: <openai_api_key>